
package com.peyrona.mingle.glue.exen.commands;

import com.peyrona.mingle.glue.ExEnClient;
import com.peyrona.mingle.glue.JTools;
import com.peyrona.mingle.glue.gswing.GButton;
import com.peyrona.mingle.glue.gswing.GList;
import com.peyrona.mingle.lang.interfaces.commands.ICommand;
import com.peyrona.mingle.lang.interfaces.commands.IDevice;
import com.peyrona.mingle.lang.interfaces.commands.IDriver;
import com.peyrona.mingle.lang.interfaces.commands.ILibrary;
import com.peyrona.mingle.lang.interfaces.commands.IRule;
import com.peyrona.mingle.lang.interfaces.commands.IScript;
import com.peyrona.mingle.lang.interfaces.network.INetClient;
import com.peyrona.mingle.lang.japi.ExEnComm;
import com.peyrona.mingle.lang.japi.UtilSys;
import com.peyrona.mingle.lang.japi.UtilUnit;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import jiconfont.icons.font_awesome.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 * Panel showing a listbox for every command and buttons to edit the highlighted.
 *
 * @author Francisco José Morero Peyrona
 *
 * Official web site at: <a href="https://github.com/peyrona/mingle">https://github.com/peyrona/mingle</a>
 */
public class PnlAllCmdsSelector
       extends javax.swing.JPanel
{
    private final ExEnClient      exenClient;
    private final GList<IScript>  ltbScrDrv;
    private final GList<IScript>  ltbScrInl;
    private final GList<IDriver>  ltbDriver;
    private final GList<ILibrary> ltbLibrary;
    private final GList<IDevice>  ltbDevice;
    private final GList<IRule>    ltbRule;
    private final CommandWise     cmdWise;

    //------------------------------------------------------------------------//
    // CONSTRUCTOR

    public PnlAllCmdsSelector( ExEnClient exenClient )
    {
        this.exenClient = exenClient;
        this.cmdWise    = new CommandWise();      // Don't move: has to be here

        initComponents();

        for( Component btn : JTools.getOfClass( this, JButton.class ) )
        {
            JButton jb = (JButton) btn;
            jb = new GButton();
        }

        ltbScrDrv  = new GList<>( lstScrDri  );
        ltbScrInl  = new GList<>( lstScrInl  );
        ltbDriver  = new GList<>( lstDriver  );
        ltbLibrary = new GList<>( lstLibrary );
        ltbRule    = new GList<>( lstRule    );
        ltbDevice  = new GList<>( lstDevice  );

        initExtra();
        refreshButtons();

        this.exenClient.add( new ClientListener() );
        this.exenClient.requestCmdList();            // Only after adding the listener, the list is requested
    }

    //------------------------------------------------------------------------//
    // PUBLIC

    public List<IDevice> getDevices()
    {
        return ltbDevice.getAll();
    }

    public void deleteAll()
    {
        List<ICommand> lstCmds = cmdWise.getAll();
        ICommand[]     aCmds   = lstCmds.toArray( ICommand[]::new );

        exenClient.sendSetOfCmds( ExEnComm.Request.Remove, aCmds );
    }

    /**
     * Directly populates the command list boxes, bypassing the network listener.
     * <p>
     * Used when loading a model into a local (in-process) ExEn where no network
     * callbacks are available to update the UI.
     *
     * @param lstCmds The commands to display.
     */
    public void loadCommands( List<ICommand> lstCmds )
    {
        SwingUtilities.invokeLater( () -> lstCmds.forEach( cmd -> added( cmd ) ) );
    }

    public String getUneSourceCode()
    {
        JTools.showWaitFrame( "Generating Une source code..." );

        StringBuilder sb = new StringBuilder( 24 * UtilUnit.KILO_BYTE );

        sb.append( "#==================================================================================================================================\n" )
          .append( "#\n" )
          .append( "# Une source code generated by Glue on " ).append( LocalDate.now() ).append( " at " ).append( LocalTime.now().truncatedTo( ChronoUnit.SECONDS ) ).append( '\n' )
          .append( "#\n" )
          .append( "#==================================================================================================================================\n\n" );

        cmdWise.getDevices().forEach( device -> sb.append( new PnlDevice( device, cmdWise ).getSourceCode() ).append( "\n\n" ) );
        cmdWise.getRules(  ).forEach( rule   -> sb.append( new PnlRule(   rule  , cmdWise ).getSourceCode() ).append( "\n\n" ) );
        cmdWise.getDrivers().forEach( driver -> sb.append( new PnlDriver( driver, cmdWise ).getSourceCode() ).append( "\n\n" ) );
        cmdWise.getScrInl( ).forEach( script -> sb.append( new PnlScrpInline( script, cmdWise ).getSourceCode() ).append( "\n\n" ) );
        cmdWise.getScrDrv( ).forEach( script -> sb.append( new PnlScrpDrv( script, cmdWise ).getSourceCode() ).append( "\n\n" ) );

        sb.append( "INCLUDE \"file://{*home.inc*}basic-drivers.une\"\n" )
          .append( "        \"file://{*home.inc*}standard-replaces.une\"\n" )
          .append( "#************************************\n" )   // TODO: find all drivers inside 'include' folder
          .append( "# Add here any other needed include *\n" )
          .append( "#************************************\n\n" );

        sb.append( "#>>>>>>>>>>>>>> EOF <<<<<<<<<<<<<<<<" );

        JTools.hideWaitFrame();

        return sb.toString();
    }

    //------------------------------------------------------------------------//
    // PRIVATE SCOPE

    /**
     * Passed request lives in the ExEn or was sent by someone (even this Glue) to the ExEn.
     *
     * @param cmd
     */
    private void added( ICommand cmd )
    {
        getListBoxFor( cmd ).add( cmd );
        refreshButtons();
    }

    /**
     * An existing request that was living in the ExEn was removed by someone (even this Glue) from the ExEn.
     *
     * @param cmd
     */
    private void removed( ICommand cmd )
    {
        getListBoxFor( cmd ).remove( cmd );
        refreshButtons();
    }

    private void clone( GList<? extends ICommand> listbox )
    {
        ICommand cmd   = listbox.getSelected();
        int      items = listbox.getAll().size();
        int      incr  = 1;                         // Used to suggest new commands name (e.g.: MyRule_1)
        String   name  = cmd.name() +'_'+ incr;

        while( true )
        {
            int n = 0;

            for( ; n < items; n++ )
            {
                if( listbox.get( n ).name().equalsIgnoreCase( name ) )
                    break;
            }

            if( n == items )
                break;
            else
                name = cmd.name() +'_'+ incr++;
        }

        exenClient.sendRequest2Clone( cmd, name );
    }

    private void del( ICommand which )
    {
        String sExtra = "";

             if( which instanceof IScript ) sExtra = "\n(all Drivers and Devices associated with this Script will be also deleted)";
        else if( which instanceof IDriver ) sExtra = "\n(all Devices associated with this Driver will be also deleted)";

        if( JTools.confirm( "Are you sure you want to delete selected command?" + sExtra ) )
        {
            exenClient.sendRequest2Del( which );

            if( ! sExtra.isEmpty() )      // When Script or Driver is sent devices will be removed but it is
            {                             // not ExEn resposibility to inform about these collateral effects
                ltbScrDrv.clear();
                ltbScrInl.clear();
                ltbDriver.clear();
                ltbLibrary.clear();
                ltbRule.clear();
                ltbDevice.clear();
            }
        }
    }

    private void edit( final Class clazz, final ICommand cmd, boolean isEditable )
    {
        final JPanel panel;

        String sErr = null;

             if( (clazz == IRule.class  ) && cmdWise.getDevices().isEmpty() ) sErr = "Can not create a RULE when the list of DEVICES is empty";
        else if( (clazz == IDevice.class) && cmdWise.getDrivers().isEmpty() ) sErr = "Can not create a DEVICE when the list of DRIVERS is empty";

        if( sErr != null )
        {
            JTools.alert( sErr );
            return;
        }

        boolean isInlineScrip = (clazz == IScript.class) && (isEditable == true);   // Because Scripts for Drivers are not editable (this is a weak way to check it but it works)

             if( clazz == IDriver.class  )  panel = new PnlDriver(     (IDriver)  cmd, cmdWise );
        else if( clazz == ILibrary.class )  panel = new PnlLibrary(    (ILibrary) cmd, cmdWise );
        else if( clazz == IDevice.class  )  panel = new PnlDevice(     (IDevice)  cmd, cmdWise, exenClient );
        else if( clazz == IRule.class    )  panel = new PnlRule(       (IRule  )  cmd, cmdWise );
        else if( isInlineScrip           )  panel = new PnlScrpInline( (IScript)  cmd, cmdWise );
        else                                panel = new PnlScrpDrv(    (IScript)  cmd, cmdWise );

        JTools.setEditable( panel, isEditable );

        String         title = clazz.getSimpleName().substring( 1 );
        ActionListener al    = null;

        if( isEditable )
        {
            al = (ActionEvent ae) ->
                                {
                                    String cmdNew = ((PnlCmdBase) panel).getTranspiled();

                                    if( cmdNew != null )
                                    {
                                        JTools.getParent( (Component) ae.getSource(), Dlg4Cmd.class ).dispose();

                                        ICommand cmd2Add = UtilSys.getConfig().newCILBuilder().build( cmdNew );

                                        if( cmd != null )
                                            exenClient.sendRequest2Replace( cmd, cmd2Add );
                                        else
                                            exenClient.sendRequest2Add( cmd2Add );
                                    }
                                };
        }

        new Dlg4Cmd( title +" Editor", panel, al ).setVisible( true );
    }

    private GList getListBoxFor( ICommand cmd )
    {
             if( cmd instanceof IDriver  )  return ltbDriver;
        else if( cmd instanceof ILibrary )  return ltbLibrary;
        else if( cmd instanceof IDevice  )  return ltbDevice;
        else if( cmd instanceof IRule    )  return ltbRule;

        // Must be an Script

        return ((IScript) cmd).isInline() ? ltbScrInl : ltbScrDrv;
    }

    private void refreshButtons()
    {
        btnScrDrvShow.setEnabled(  ltbScrDrv.isNotEmpty()  );

        btnScrInlEdit.setEnabled(  ltbScrInl.isNotEmpty()  );
        btnScrInlClone.setEnabled( ltbScrInl.isNotEmpty()  );
        btnScrInlDel.setEnabled(   ltbScrInl.isNotEmpty()  );

        btnDriverShow.setEnabled(  ltbDriver.isNotEmpty()  );
     // btnDriverClone.setEnabled( ltbDriver.isNotEmpty()  );   NOT USED
     // btnDriverDel.setEnabled(   ltbDriver.isNotEmpty()  );   NOT USED

        btnLibraryEdit.setEnabled( ltbLibrary.isNotEmpty() );
        btnLibraryDel.setEnabled(  ltbLibrary.isNotEmpty() );

        btnRuleEdit.setEnabled(    ltbRule.isNotEmpty()    );
        btnRuleClone.setEnabled(   ltbRule.isNotEmpty()    );
        btnRuleDel.setEnabled(     ltbRule.isNotEmpty()    );

        btnDeviceEdit.setEnabled(  ltbDevice.isNotEmpty()  );
        btnDeviceClone.setEnabled( ltbDevice.isNotEmpty()  );
        btnDeviceDel.setEnabled(   ltbDevice.isNotEmpty()  );
    }

    private void initExtra()
    {
        Icon iconNew   = IconFontSwing.buildIcon( FontAwesome.PLUS  , 16, JTools.getIconColor() );
        Icon iconEdit  = IconFontSwing.buildIcon( FontAwesome.PENCIL, 16, JTools.getIconColor() );
        Icon iconClone = IconFontSwing.buildIcon( FontAwesome.CLONE , 16, JTools.getIconColor() );
        Icon iconDel   = IconFontSwing.buildIcon( FontAwesome.TRASH , 16, JTools.getIconColor() );
        Icon iconShow  = IconFontSwing.buildIcon( FontAwesome.EYE   , 16, JTools.getIconColor() );

        ltbScrDrv.setCaptionFn(  (cmd) -> cmd.name() );
        ltbScrInl.setCaptionFn(  (cmd) -> cmd.name() );
        ltbDriver.setCaptionFn(  (cmd) -> cmd.name() );
        ltbLibrary.setCaptionFn( (cmd) -> cmd.name() );
        ltbDevice.setCaptionFn(  (cmd) -> cmd.name() );
        ltbRule.setCaptionFn(    (cmd) -> cmd.name() );

        ltbScrDrv.onPicked(  (list) -> edit( IScript.class , list.getSelected(), false ) );
        ltbScrInl.onPicked(  (list) -> edit( IScript.class , list.getSelected(), true  ) );
        ltbDriver.onPicked(  (list) -> edit( IDriver.class , list.getSelected(), false ) );
        ltbLibrary.onPicked( (list) -> edit( ILibrary.class, list.getSelected(), false ) );
        ltbDevice.onPicked(  (list) -> edit( IDevice.class , list.getSelected(), true  ) );
        ltbRule.onPicked(    (list) -> edit( IRule.class   , list.getSelected(), true  ) );

        btnScrDrvShow.setIcon( iconShow );
        btnScrDrvShow.addActionListener(  evt -> edit( IScript.class, ltbScrDrv.getSelected(), false ) );

        btnScrInlNew.setIcon(   iconNew   );
        btnScrInlEdit.setIcon(  iconEdit  );
        btnScrInlClone.setIcon( iconClone );
        btnScrInlDel.setIcon(   iconDel   );
        btnScrInlNew.addActionListener(   evt -> edit( IScript.class, null                   , true ) );
        btnScrInlEdit.addActionListener(  evt -> edit( IScript.class, ltbScrInl.getSelected(), true ) );
        btnScrInlClone.addActionListener( evt -> clone( ltbScrInl ) );
        btnScrInlDel.addActionListener(   evt -> del(   ltbScrInl.getSelected() ) );

        btnDriverShow.setIcon( iconShow );
        btnDriverNew.setIcon(  iconNew  );
        btnDriverClone.setVisible( false );    // ACTION NOT ALLOWED YET
        btnDriverDel.setVisible(   false );    // ACTION NOT ALLOWED YET
        btnDriverShow.addActionListener( evt -> edit( IDriver.class, ltbDriver.getSelected(), false ) );
        btnDriverNew.addActionListener(  evt -> edit( IDriver.class, null                   , true  ) );

        btnLibraryNew.setIcon(  iconNew  );
        btnLibraryEdit.setIcon( iconEdit );
        btnLibraryDel.setIcon(  iconDel  );
        btnLibraryNew.addActionListener(   evt -> edit( ILibrary.class, null                    , true ) );
        btnLibraryEdit.addActionListener(  evt -> edit( ILibrary.class, ltbLibrary.getSelected(), true ) );
        btnLibraryDel.addActionListener(   evt -> del(  ltbLibrary.getSelected() ) );

        btnDeviceNew.setIcon(   iconNew   );
        btnDeviceEdit.setIcon(  iconEdit  );
        btnDeviceClone.setIcon( iconClone );
        btnDeviceDel.setIcon(   iconDel   );
        btnDeviceNew.addActionListener(   evt -> edit( IDevice.class, null                   , true ) );
        btnDeviceEdit.addActionListener(  evt -> edit( IDevice.class, ltbDevice.getSelected(), true ) );
        btnDeviceClone.addActionListener( evt -> clone( ltbDevice ) );
        btnDeviceDel.addActionListener(   evt -> del(   ltbDevice.getSelected() ) );

        btnRuleNew.setIcon(   iconNew );
        btnRuleEdit.setIcon(  iconEdit );
        btnRuleClone.setIcon( iconClone );
        btnRuleDel.setIcon(   iconDel );
        btnRuleNew.addActionListener(   evt -> edit( IRule.class, null                 , true ) );
        btnRuleEdit.addActionListener(  evt -> edit( IRule.class, ltbRule.getSelected(), true ) );
        btnRuleClone.addActionListener( evt -> clone( ltbRule ) );
        btnRuleDel.addActionListener(   evt -> del(   ltbRule.getSelected() ) );
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblRules = new javax.swing.JLabel();
        btnRuleNew = new GButton();
        btnRuleEdit = new GButton();
        btnRuleClone = new GButton();
        btnRuleDel = new GButton();
        spRule = new javax.swing.JScrollPane();
        lstRule = new javax.swing.JList<>();
        lblDevices = new javax.swing.JLabel();
        btnDeviceNew = new GButton();
        btnDeviceEdit = new GButton();
        btnDeviceClone = new GButton();
        btnDeviceDel = new GButton();
        spDevice = new javax.swing.JScrollPane();
        lstDevice = new javax.swing.JList<>();
        lblDrivers = new javax.swing.JLabel();
        btnDriverShow = new GButton();
        btnDriverNew = new GButton();
        btnDriverClone = new GButton();
        btnDriverDel = new GButton();
        spDriver = new javax.swing.JScrollPane();
        lstDriver = new javax.swing.JList<>();
        lblScrInline = new javax.swing.JLabel();
        btnScrInlNew = new GButton();
        btnScrInlEdit = new GButton();
        btnScrInlClone = new GButton();
        btnScrInlDel = new GButton();
        spScrDriver = new javax.swing.JScrollPane();
        lstScrDri = new javax.swing.JList<>();
        spScrInline = new javax.swing.JScrollPane();
        lstScrInl = new javax.swing.JList<>();
        lblScrDriver = new javax.swing.JLabel();
        btnScrDrvShow = new GButton();
        lblLibrary = new javax.swing.JLabel();
        spLibrary = new javax.swing.JScrollPane();
        lstLibrary = new javax.swing.JList<>();
        btnLibraryDel = new GButton();
        btnLibraryEdit = new GButton();
        btnLibraryNew = new GButton();

        setPreferredSize(new java.awt.Dimension(760, 680));

        lblRules.setFont(lblRules.getFont().deriveFont(lblRules.getFont().getStyle() | java.awt.Font.BOLD, lblRules.getFont().getSize()+2));
        lblRules.setText("Rules");

        btnRuleNew.setToolTipText("Create new item");
        btnRuleNew.setFocusPainted(false);

        btnRuleEdit.setToolTipText("Edit highlighted item");
        btnRuleEdit.setFocusPainted(false);

        btnRuleClone.setToolTipText("Clone highlighted item");
        btnRuleClone.setFocusPainted(false);

        btnRuleDel.setToolTipText("Remove highlighted item");
        btnRuleDel.setFocusPainted(false);

        lstRule.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstRule.setVisibleRowCount(12);
        spRule.setViewportView(lstRule);

        lblDevices.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        lblDevices.setText("Devices");

        btnDeviceNew.setToolTipText("Create new item");
        btnDeviceNew.setFocusPainted(false);

        btnDeviceEdit.setToolTipText("Edit highlighted item");
        btnDeviceEdit.setFocusPainted(false);

        btnDeviceClone.setToolTipText("Clone highlighted item");
        btnDeviceClone.setFocusPainted(false);

        btnDeviceDel.setToolTipText("Remove highlighted item");
        btnDeviceDel.setFocusPainted(false);

        lstDevice.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstDevice.setVisibleRowCount(12);
        spDevice.setViewportView(lstDevice);

        lblDrivers.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        lblDrivers.setText("Drivers");

        btnDriverShow.setToolTipText("Create new item");
        btnDriverShow.setFocusPainted(false);

        btnDriverNew.setToolTipText("Edit highlighted item");
        btnDriverNew.setFocusPainted(false);

        btnDriverClone.setToolTipText("Clone highlighted item");
        btnDriverClone.setFocusPainted(false);

        btnDriverDel.setToolTipText("Remove highlighted item");
        btnDriverDel.setFocusPainted(false);

        lstDriver.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstDriver.setVisibleRowCount(12);
        spDriver.setViewportView(lstDriver);

        lblScrInline.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        lblScrInline.setText("Scripts (Inline)");

        btnScrInlNew.setToolTipText("Create new item");
        btnScrInlNew.setFocusPainted(false);

        btnScrInlEdit.setToolTipText("Edit highlighted item");
        btnScrInlEdit.setFocusPainted(false);

        btnScrInlClone.setToolTipText("Clone highlighted item");
        btnScrInlClone.setFocusPainted(false);

        btnScrInlDel.setToolTipText("Remove highlighted item");
        btnScrInlDel.setFocusPainted(false);

        lstScrDri.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstScrDri.setVisibleRowCount(12);
        spScrDriver.setViewportView(lstScrDri);

        lstScrInl.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstScrInl.setVisibleRowCount(12);
        spScrInline.setViewportView(lstScrInl);

        lblScrDriver.setFont(lblScrDriver.getFont().deriveFont(lblScrDriver.getFont().getStyle() | java.awt.Font.BOLD));
        lblScrDriver.setText("Scripts (all others)");

        btnScrDrvShow.setToolTipText("Create new item");
        btnScrDrvShow.setFocusPainted(false);

        lblLibrary.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        lblLibrary.setText("Libraries");

        lstLibrary.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstLibrary.setVisibleRowCount(12);
        spLibrary.setViewportView(lstLibrary);

        btnLibraryDel.setToolTipText("Create new item");
        btnLibraryDel.setFocusPainted(false);

        btnLibraryEdit.setToolTipText("Create new item");
        btnLibraryEdit.setFocusPainted(false);

        btnLibraryNew.setToolTipText("Create new item");
        btnLibraryNew.setFocusPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRules)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnRuleNew)
                                .addComponent(btnRuleEdit)
                                .addComponent(btnRuleClone))
                            .addComponent(btnRuleDel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spRule, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeviceNew, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDeviceEdit, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDeviceClone, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDeviceDel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spDevice, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addComponent(lblDevices))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDriverShow)
                            .addComponent(btnDriverNew)
                            .addComponent(btnDriverDel)
                            .addComponent(btnDriverClone, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spDriver, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addComponent(lblDrivers))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnScrDrvShow)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spScrDriver, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE))
                    .addComponent(lblScrInline)
                    .addComponent(lblScrDriver)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnScrInlNew)
                            .addComponent(btnScrInlEdit)
                            .addComponent(btnScrInlDel)
                            .addComponent(btnScrInlClone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spScrInline, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLibraryNew)
                            .addComponent(btnLibraryEdit)
                            .addComponent(btnLibraryDel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spLibrary, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                    .addComponent(lblLibrary))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnLibraryDel, btnLibraryEdit, btnLibraryNew, btnScrInlEdit});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDrivers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDriverShow)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDriverNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDriverClone)
                                .addGap(18, 18, 18)
                                .addComponent(btnDriverDel))
                            .addComponent(spDriver)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblScrInline)
                            .addComponent(lblLibrary))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spScrInline, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnScrInlNew)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnScrInlEdit)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnScrInlClone)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnScrInlDel))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnLibraryNew)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnLibraryEdit)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnLibraryDel)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(lblScrDriver)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(spScrDriver, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnScrDrvShow)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(spLibrary)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblDevices)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDeviceNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeviceEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeviceClone)
                                .addGap(18, 18, 18)
                                .addComponent(btnDeviceDel))
                            .addComponent(spDevice)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRules)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnRuleNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRuleEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRuleClone)
                                .addGap(18, 18, 18)
                                .addComponent(btnRuleDel)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(spRule))))
                .addGap(9, 9, 9))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnLibraryNew, btnScrInlEdit});

    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeviceClone;
    private javax.swing.JButton btnDeviceDel;
    private javax.swing.JButton btnDeviceEdit;
    private javax.swing.JButton btnDeviceNew;
    private javax.swing.JButton btnDriverClone;
    private javax.swing.JButton btnDriverDel;
    private javax.swing.JButton btnDriverNew;
    private javax.swing.JButton btnDriverShow;
    private javax.swing.JButton btnLibraryDel;
    private javax.swing.JButton btnLibraryEdit;
    private javax.swing.JButton btnLibraryNew;
    private javax.swing.JButton btnRuleClone;
    private javax.swing.JButton btnRuleDel;
    private javax.swing.JButton btnRuleEdit;
    private javax.swing.JButton btnRuleNew;
    private javax.swing.JButton btnScrDrvShow;
    private javax.swing.JButton btnScrInlClone;
    private javax.swing.JButton btnScrInlDel;
    private javax.swing.JButton btnScrInlEdit;
    private javax.swing.JButton btnScrInlNew;
    private javax.swing.JLabel lblDevices;
    private javax.swing.JLabel lblDrivers;
    private javax.swing.JLabel lblLibrary;
    private javax.swing.JLabel lblRules;
    private javax.swing.JLabel lblScrDriver;
    private javax.swing.JLabel lblScrInline;
    private javax.swing.JList<IDevice> lstDevice;
    private javax.swing.JList<IDriver> lstDriver;
    private javax.swing.JList<ILibrary> lstLibrary;
    private javax.swing.JList<IRule> lstRule;
    private javax.swing.JList<IScript> lstScrDri;
    private javax.swing.JList<IScript> lstScrInl;
    private javax.swing.JScrollPane spDevice;
    private javax.swing.JScrollPane spDriver;
    private javax.swing.JScrollPane spLibrary;
    private javax.swing.JScrollPane spRule;
    private javax.swing.JScrollPane spScrDriver;
    private javax.swing.JScrollPane spScrInline;
    // End of variables declaration//GEN-END:variables

    //------------------------------------------------------------------------//
    // INNER CLASS
    // Instrumentation class similar to IRuntime that provides access to all
    // existing IComands in this ExEn
    //------------------------------------------------------------------------//
    public final class CommandWise
    {
        public List<ICommand> getAll()
        {
            List<ICommand> lstCmds = new ArrayList<>();

            lstCmds.addAll( getScrInl()    );
            lstCmds.addAll( getScrDrv()    );
            lstCmds.addAll( getLibraries() );
            lstCmds.addAll( getDrivers()   );
            lstCmds.addAll( getRules()     );
            lstCmds.addAll( getDevices()   );

            return lstCmds;
        }

        public List<IScript> getScrInl()
        {
            return ltbScrInl.getAll();
        }

        public List<IScript> getScrDrv()
        {
            return ltbScrDrv.getAll();
        }

        public List<IDriver> getDrivers()
        {
            return ltbDriver.getAll();
        }

        public List<ILibrary> getLibraries()
        {
            return ltbLibrary.getAll();
        }

        public List<IRule> getRules()
        {
            return ltbRule.getAll();
        }

        public List<IDevice> getDevices()
        {
            return ltbDevice.getAll();
        }

        public boolean isScript( String name )
        {
            for( IScript scp : getScrInl() )
            {
                if( scp.name().equals( name ) )
                    return true;
            }

            return false;
        }

        public boolean isDriver( String name )
        {
            for( IDriver drv : getDrivers() )
            {
                if( drv.name().equals( name ) )
                    return true;
            }

            return false;
        }

        public boolean isRule( String name )
        {
            for( IRule rul : getRules() )
            {
                if( rul.name().equals( name ) )
                    return true;
            }

            return false;
        }

        public Set<String> getGroups( List<? extends IDevice> lstDevices )
        {
            Set<String> set = new HashSet<>();

            for( IDevice device : lstDevices )
                set.addAll( Arrays.asList( device.groups() ) );

            return set;
        }

        //------------------------------------------------------------------------//
        // PRIVATE CONSTRUCTOR

        private CommandWise()
        {
        }
    }

    //------------------------------------------------------------------------//
    // INNER CLASS
    // This listener is in charge of react when connection is started, is ended
    // or an error happens: this is common to all instances of ExEnClient class.
    //------------------------------------------------------------------------//

    private final class ClientListener implements INetClient.IListener
    {
        @Override
        public void onConnected( INetClient origin )
        {
        }

        @Override
        public void onDisconnected( INetClient origin )
        {
        }

        @Override
        public void onError( INetClient origin, Exception exc )
        {
        }

        @Override
        public void onMessage( INetClient origin, String sJSON )
        {
            ExEnComm msg = ExEnComm.fromJSON( sJSON );

            SwingUtilities.invokeLater( () ->
                {
                    switch( msg.request )
                    {
                        case Listed:
                        case Added :
                            for( ICommand cmd : msg.getCommands() )
                                PnlAllCmdsSelector.this.added( cmd );

                            break;

                        case Removed:
                            for( ICommand cmd : msg.getCommands() )
                                PnlAllCmdsSelector.this.removed( cmd );

                            break;

                        case Error:
                            JTools.error( "Error received from ExEn at:"+ origin +"\n\n"+ msg.getErrorMsg() );
                            break;
                    }
                } );
        }
    }
}