
package com.peyrona.mingle.glue.exen.commands;

import com.peyrona.mingle.glue.JTools;
import com.peyrona.mingle.glue.gswing.GButton;
import com.peyrona.mingle.lang.japi.UtilColls;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.HashMap;
import java.util.Map;
import javax.swing.table.DefaultTableModel;
import jiconfont.icons.font_awesome.FontAwesome;
import jiconfont.swing.IconFontSwing;

/**
 * A panel to configure the CONFIG clause: used by DEVICE and LIBRAY
 * @author francisco
 */
public final class PnlAux4Config extends javax.swing.JPanel
{
    /**
     * Creates new form PnlAux4Config
     */
    public PnlAux4Config()
    {
        initComponents();

        btnAddRow.setIcon( IconFontSwing.buildIcon( FontAwesome.PLUS , 16, JTools.getIconColor() ) );
        btnDelRow.setIcon( IconFontSwing.buildIcon( FontAwesome.TRASH, 16, JTools.getIconColor() ) );

        tblConfig.addMouseListener( new MouseAdapter()
        {
            @Override
            public void mouseClicked( MouseEvent e )
            {
                if( e.getClickCount() == 2 )
                {
                    int row = tblConfig.rowAtPoint( e.getPoint() );
                    int col = tblConfig.columnAtPoint( e.getPoint() );

                    if( row >= 0 && col >= 0 )
                    {
                        tblConfig.editCellAt( row, col );
                    }
                }
            }
        });
    }

    //------------------------------------------------------------------------//
    // PUBLIC SCOPE

    /**
     * Returns the configuration as a map of key-value pairs.
     * <p>
     * Rows with blank or null names are skipped. Keys are converted to
     * lowercase to match the transpiler convention.
     *
     * @return a map with the configuration entries (never {@code null}).
     */
    public Map<String,Object> getConfig()
    {
        stopEditing();

        DefaultTableModel  model  = (DefaultTableModel) tblConfig.getModel();
        Map<String,Object> config = new HashMap<>();

        for( int row = 0; row < model.getRowCount(); row++ )
        {
            Object oName  = model.getValueAt( row, 0 );
            Object oValue = model.getValueAt( row, 1 );

            if( oName == null )
                continue;

            String name = oName.toString().trim();

            if( name.isEmpty() )
                continue;

            config.put( name.toLowerCase(), (oValue != null ? oValue : "") );
        }

        return config;
    }

    /**
     * Populates the table with the entries from the given configuration map.
     * <p>
     * Any previous content in the table is removed before loading.
     *
     * @param config the configuration to load ({@code null} or empty clears the table).
     */
    public void setConfig( Map<String,Object> config )
    {
        stopEditing();

        DefaultTableModel model = (DefaultTableModel) tblConfig.getModel();
                          model.setRowCount( 0 );

        if( config != null )
        {
            for( Map.Entry<String,Object> entry : config.entrySet() )
            {
                model.addRow( new Object[]{ entry.getKey(), entry.getValue() } );
            }
        }
    }

    public String getSourceCode()
    {
        Map<String,Object> map = getConfig();

        if( UtilColls.isEmpty( map ) )
            return "";

        StringBuilder sb = new StringBuilder( 512 );

        for( Map.Entry<String,Object> entry : map.entrySet() )
        {
            // FIXME: hacerlo
        }

        return "\n\tCONFIG "+ sb.toString();
    }

    //------------------------------------------------------------------------//

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlDriverConfig = new javax.swing.JPanel();
        btnAddRow = new GButton();
        btnDelRow = new GButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConfig = new javax.swing.JTable();

        pnlDriverConfig.setBorder(javax.swing.BorderFactory.createTitledBorder(" CONFIG "));

        btnAddRow.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAddRowActionPerformed(evt);
            }
        });

        btnDelRow.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDelRowActionPerformed(evt);
            }
        });

        tblConfig.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String []
            {
                "Name", "Value"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }
        });
        tblConfig.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblConfig);

        javax.swing.GroupLayout pnlDriverConfigLayout = new javax.swing.GroupLayout(pnlDriverConfig);
        pnlDriverConfig.setLayout(pnlDriverConfigLayout);
        pnlDriverConfigLayout.setHorizontalGroup(
            pnlDriverConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDriverConfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addGap(14, 14, 14)
                .addGroup(pnlDriverConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddRow)
                    .addComponent(btnDelRow))
                .addContainerGap())
        );
        pnlDriverConfigLayout.setVerticalGroup(
            pnlDriverConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDriverConfigLayout.createSequentialGroup()
                .addGroup(pnlDriverConfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDriverConfigLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnAddRow)
                        .addGap(18, 18, 18)
                        .addComponent(btnDelRow))
                    .addGroup(pnlDriverConfigLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDriverConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDriverConfig, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddRowActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddRowActionPerformed
    {//GEN-HEADEREND:event_btnAddRowActionPerformed
        stopEditing();

        DefaultTableModel model = (DefaultTableModel) tblConfig.getModel();
        model.addRow( new Object[]{ null, null } );

        int lastRow = model.getRowCount() - 1;
        tblConfig.setRowSelectionInterval( lastRow, lastRow );
        tblConfig.scrollRectToVisible( tblConfig.getCellRect( lastRow, 0, true ) );
        tblConfig.editCellAt( lastRow, 0 );

        if( tblConfig.getEditorComponent() != null )
        {
            tblConfig.getEditorComponent().requestFocusInWindow();
        }
    }//GEN-LAST:event_btnAddRowActionPerformed

    private void btnDelRowActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDelRowActionPerformed
    {//GEN-HEADEREND:event_btnDelRowActionPerformed
        int selectedRow = tblConfig.getSelectedRow();

        if( selectedRow < 0 )
            return;

        stopEditing();

        DefaultTableModel model = (DefaultTableModel) tblConfig.getModel();
        model.removeRow( selectedRow );

        // Select the nearest remaining row
        int rowCount = model.getRowCount();

        if( rowCount > 0 )
        {
            int newSelection = Math.min( selectedRow, rowCount - 1 );
            tblConfig.setRowSelectionInterval( newSelection, newSelection );
        }
    }//GEN-LAST:event_btnDelRowActionPerformed


    //------------------------------------------------------------------------//
    // PRIVATE SCOPE

    /**
     * Commits any in-progress cell editing before modifying the model.
     */
    private void stopEditing()
    {
        if( tblConfig.isEditing() )
            tblConfig.getCellEditor().stopCellEditing();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRow;
    private javax.swing.JButton btnDelRow;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pnlDriverConfig;
    private javax.swing.JTable tblConfig;
    // End of variables declaration//GEN-END:variables
}
