
package com.peyrona.mingle.glue.exen.commands;

import com.peyrona.mingle.glue.JTools;
import com.peyrona.mingle.lang.MingleException;
import com.peyrona.mingle.lang.japi.UtilType;
import com.peyrona.mingle.lang.lexer.Language;
import javax.swing.JTextField;

/**
 *
 * @author Francisco José Morero Peyrona
 *
 * Official web site at: <a href="https://github.com/peyrona/mingle">https://github.com/peyrona/mingle</a>
 */
final class PnlChangeActuator extends javax.swing.JPanel
{
    /**
     * Creates new form PnlChangeActuator
     */
    PnlChangeActuator()
    {
        initComponents();
    }

    //------------------------------------------------------------------------//

    Object getValue()
    {
        Object value = null;

        try
        {
                 if( radBoolean.isSelected() ) value = UtilType.toBoolean( txtValue.getText() );
            else if( radNumber.isSelected()  ) value = UtilType.toFloat(   txtValue.getText() );
            else                               value = txtValue.getText();   // No trim

            if( value == null )
                throw new NullPointerException();
        }
        catch( MingleException | NullPointerException | NumberFormatException exc )
        {
            JTools.alert( "Error converting value" );
        }

        return value;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        radioBtnGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtValue = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        radNumber = new javax.swing.JRadioButton();
        radString = new javax.swing.JRadioButton();
        radBoolean = new javax.swing.JRadioButton();

        jLabel1.setText("New value");

        txtValue.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtValueKeyReleased(evt);
            }
        });

        jLabel2.setText("Send as: ");

        radioBtnGroup.add(radNumber);
        radNumber.setSelected(true);
        radNumber.setText("Number");

        radioBtnGroup.add(radString);
        radString.setText("String");

        radioBtnGroup.add(radBoolean);
        radBoolean.setText("Boolean");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtValue)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(radNumber)
                        .addGap(18, 18, 18)
                        .addComponent(radString)
                        .addGap(18, 18, 18)
                        .addComponent(radBoolean)
                        .addContainerGap(73, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(radNumber)
                    .addComponent(radString)
                    .addComponent(radBoolean))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtValueKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtValueKeyReleased
    {//GEN-HEADEREND:event_txtValueKeyReleased
        String text = ((JTextField) evt.getComponent()).getText().trim();

             if( Language.isBooleanValue( text ) )  radBoolean.setSelected( true );
        else if( Language.isNumber( text ) )        radNumber.setSelected( true );
        else                                        radString.setSelected( true );
    }//GEN-LAST:event_txtValueKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton radBoolean;
    private javax.swing.JRadioButton radNumber;
    private javax.swing.JRadioButton radString;
    private javax.swing.ButtonGroup radioBtnGroup;
    private javax.swing.JTextField txtValue;
    // End of variables declaration//GEN-END:variables
}
