
package com.peyrona.mingle.glue.exen.commands;

import com.peyrona.mingle.lang.interfaces.commands.IDriver;

/**
 * Panel for configuring and managing driver commands.
 * <p>
 * This panel provides UI components to create and edit driver definitions
 * in the Mingle system. It allows users to specify driver names and
 * associated script names. Currently marked as "NOT YET IMPLEMENTED"
 * indicating this is a work in progress.
 *
 * @author Francisco José Morero Peyrona
 *
 * Official web site at: <a href="https://github.com/peyrona/mingle">https://github.com/peyrona/mingle</a>
 */
final class PnlDriver extends PnlCmdBase
{
    public PnlDriver( IDriver driver, PnlAllCmdsSelector.CommandWise cmdWise )
    {
        super( cmdWise );

        initComponents();

        if( driver == null )
            return;

        txtName.setText( driver.name() );
        txtScript.setText( driver.getScriptName() );
    }

    //------------------------------------------------------------------------//

    @Override
    public String getSourceCode()
    {
        return "";
    }

    @Override
    public String getTranspiled()
    {
        return null;     // Drivers themselves can not be changed on the fly
    }

    //------------------------------------------------------------------------//

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtScript = new javax.swing.JTextField();

        jLabel4.setText("jLabel4");

        jLabel1.setText("Driver Name");

        txtName.setEditable(false);
        txtName.setFocusTraversalPolicyProvider(true);
        txtName.setName("ControlName"); // NOI18N

        jLabel2.setText("Script name");

        txtScript.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName)
                    .addComponent(txtScript, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtScript, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtScript;
    // End of variables declaration//GEN-END:variables
}