/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.peyrona.mingle.stick;

import com.eclipsesource.json.Json;
import com.eclipsesource.json.JsonObject;
import com.eclipsesource.json.JsonValue;
import com.eclipsesource.json.ParseException;
import com.peyrona.mingle.lang.MingleException;
import com.peyrona.mingle.lang.interfaces.ICandi;
import com.peyrona.mingle.lang.interfaces.ICmdEncDecLib;
import com.peyrona.mingle.lang.interfaces.IConfig;
import com.peyrona.mingle.lang.interfaces.ILogger;
import com.peyrona.mingle.lang.interfaces.IXprEval;
import com.peyrona.mingle.lang.interfaces.commands.ICommand;
import com.peyrona.mingle.lang.interfaces.commands.IDevice;
import com.peyrona.mingle.lang.interfaces.commands.IDriver;
import com.peyrona.mingle.lang.interfaces.commands.ILibrary;
import com.peyrona.mingle.lang.interfaces.commands.IRule;
import com.peyrona.mingle.lang.interfaces.commands.IScript;
import com.peyrona.mingle.lang.interfaces.exen.IEventBus;
import com.peyrona.mingle.lang.interfaces.exen.IRuntime;
import com.peyrona.mingle.lang.japi.Config;
import com.peyrona.mingle.lang.japi.UtilStr;
import com.peyrona.mingle.lang.japi.UtilSys;
import com.peyrona.mingle.lang.japi.UtilUnit;
import com.peyrona.mingle.lang.messages.Message;
import com.peyrona.mingle.lang.messages.MsgChangeActuator;
import com.peyrona.mingle.lang.messages.MsgDeviceChanged;
import com.peyrona.mingle.lang.messages.MsgDeviceReaded;
import com.peyrona.mingle.lang.messages.MsgExecute;
import com.peyrona.mingle.lang.messages.MsgReadDevice;
import com.peyrona.mingle.lang.xpreval.functions.StdXprFns;
import com.peyrona.mingle.lang.xpreval.functions.list;
import java.io.File;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

/**
 * This class provides the execution environment where the transpiled Une code is executed.<br>
 * <br>>
 * Although it is not frequent, several ExEn instances could coexists even in the same
 * JVM: it is responsibility of the application that creates the instances to properly
 * manage them.<br>
 * <br>>
 * Because messages inside an ExEn are main generated by devices and because there is a very
 * limited amount of devices, I was thinking to reuse the same messages and simply change its
 * value.<br>
 * After thinking, this is not a good idea: the performance gain from reusing message
 * instances is negligible compared to the risk of race conditions and data corruption.
 *
 * @author Francisco José Morero Peyrona
 *
 * Official web site at: <a href="https://github.com/peyrona/mingle">https://github.com/peyrona/mingle</a>
 */
public final class Stick
             implements IRuntime
{
    private final    IConfig        config;     // Can not be sat as UtilSys.setConfig(...) because each instance of Stick can have its own instance of IConfig
    private final    IEventBus      eventBus;
    private final    GridManager    gridMgr;
    private final    LibraryManager librMgr;
    private final    ScriptManager  srptMgr;
    private final    DriverManager  drvrMgr;
    private final    DeviceManager  deviMgr;
    private final    RuleManager    ruleMgr;
    private volatile boolean        keepRun = true;
    private volatile boolean        bExited = false;

    //----------------------------------------------------------------------------//
    // CONSTRUCTOR

    // Exceptions thrown inside the constructor (and methods it calls) will stop Stick: this is the intention.
    // But once Stick is running, exceptions thrown should do not stop Stick.

    /**
     * Starts Stick: the MSP Environment Executor (ExEn) with no model and no configuration file.
     */
    public Stick()
    {
        this( null, null );
    }

    /**
     * Starts Stick: the MSP Environment Executor (ExEn).
     *
     * @param sModelJSON  An string containing a valid JSON: this is the transpiled Une code to be executed. It can be empty.
     * @param config      An instance holding the ".json" configuration that will be used; can be null.
     */
    public Stick( String sModelJSON, IConfig config )
    {
        try
        {
            config = ((config == null) ? new Config().load( null ) : config);
        }
        catch( IOException ioe )
        {
            failed( ioe, null );
        }

        this.config = config;

        // These are also needed here (besides Main.java) because this class can be instatiated directly (without passing it by Main.java)

        UtilSys.setConfig( config );
        UtilSys.setLogger( "stick", config );

        if( UtilSys.getRuntime() != null )
            failed( null, "Only one instance of '"+ getClass().getName() +"' is allowed per JVM" );

        UtilSys.setRuntime( this );

        // Creates and assigns a SLF4J Provider to redirect SLF4J logs to Mingle default Logger (I also removed the SLF4J JAR from the Stick project)
        // SLF4J_Adapter.init( logger );
        // System.setProperty( "slf4j.provider", SLF4J_Provider.class.getName() );

        // After Logger is initialized, the rest of modules can be initialized too

        eventBus = new EventBus( config.get( "exen", "bus_capacity", 2048 ) );
        librMgr  = new LibraryManager( this );   // Instantiated first: libraries must load before scripts run
        srptMgr  = new ScriptManager(  this );
        drvrMgr  = new DriverManager(  this );
        deviMgr  = new DeviceManager(  this );
        ruleMgr  = new RuleManager(    this );
        gridMgr  = GridManager.create( config, (IRuntime) this, this::failed );

        // Loads transpiled code (if any) and adds commands to their managers

        addModel( sModelJSON );

        // By using a hook we maximize the possibilities the finalization code will be
        // invoked: even if INTERRUPT signal (Ctrl-C) is used, the JVM will invoke this hook.
        // Even when System.exit(...) is used, the JVM will invoke this hook.

        Runtime.getRuntime()
               .addShutdownHook( new Thread( () -> stop() ) );
    }

    //------------------------------------------------------------------------//

    /**
     * Starts stick with the parameters passed at class constructor.
     *
     * @return Itself.
     */
    public Stick start()
    {
        return start( null );
    }

    /**
     * Starts stick with the parameters passed at class constructor.
     * @param sModelName When not null, it is used only to be displayed in welcome screen.
     *
     * @return Itself.
     */
    public Stick start( String sModelName )
    {
        say( "Stick: An 'Execution Environment' (ExEn) for the 'Mingle Standard Platform' (MSP).\n" +
             "       Version "+ UtilSys.getVersion( getClass() ) );   // Do not move this: for clarity, the best is to start with this message

        if( UtilStr.isMeaningless( sModelName ) )
            sModelName = deviMgr.isEmpty() ? "None" : "Unknown";    // "None" means that no model was provided. "Unknown" means that a model was provided but its name is unknown
        else
            sModelName = sModelName.trim();

        librMgr.start();    // Libraries must be available before any script runs (including PRE ONSTART)

        srptMgr.runPreStartScripts();

        srptMgr.start();   // Prepares scripts; ONSTART are executed (as it is done by posting an msg into the bus, entites will exist when it will be executed)
        GridManager.start( gridMgr, this, deviMgr, ruleMgr, srptMgr, this::failed, this::runVoidThread );   // GridManager instance is needed before creating the Commands because Rule (perhaps also others) use ::isGridNode()
        drvrMgr.start();   // Drivers has to be inited before devices because devices ask for their values to drivers
        deviMgr.start();   // After starting every device, it requests its value and generates a Device Changes message
        ruleMgr.start();

        //------------------------------------------------------------------------//

        boolean bUseDisk  = UtilSys.isFsWritable && config.get( "exen", "write_disk", true  );
        boolean bFakeDrvs = config.get( "exen", "faked_drivers", false );
        boolean bDocker   = UtilSys.isDocker();
        String  sLogName  = UtilSys.getLogger().getName();
        String  sLogLevel = UtilSys.getLogger().getLevel().toString();
        String  sGridMsg  = System.getProperty( "_GridManager_toString_Message_" );   // This is created in ::initGridManager()

        Runtime runtime   = Runtime.getRuntime();
        long    nMaxRAM   = runtime.maxMemory()   / UtilUnit.MEGA_BYTE;
        long    nTotRAM   = runtime.totalMemory() / UtilUnit.MEGA_BYTE;
        long    nUsedRAM  = (runtime.totalMemory() - runtime.freeMemory()) / UtilUnit.MEGA_BYTE;

        String sInfo = new StringBuilder()
                .append( '\n' )
                .append( "Model   = "         ).append( sModelName ).append( '\n' )
                .append( "Config  = "         ).append( config.getURI() ).append( '\n' )
                .append( "Home    = "         ).append( UtilSys.fHomeDir ).append( '\n' )
                .append( "Log     = "         ).append( new File( UtilSys.getLogDir(), sLogName ) ).append( ", Level=" ).append( sLogLevel ).append( '\n' )
                .append( "XprEval = "         ).append( config.newXprEval().about() ).append( '\n' )
                .append( "Cmd Lib = "         ).append( config.newCILBuilder().about() ).append( '\n' )
                .append( "UseDisk = "         ).append( bUseDisk ).append( " -> Local storage is used to read" ).append( bUseDisk ? " and to write" : "-only").append( '\n' )
                .append( "Faked   = "         ).append( bFakeDrvs ).append( bFakeDrvs ? " -> Using faked drivers" : " -> Using real drivers" ).append( '\n' )
                .append( "User    = "         ).append( System.getProperty( "user.name" ) ).append( ", home: ").append( System.getProperty( "user.home" ) ).append( '\n' )
                .append( "Java    = version " ).append( System.getProperty( "java.version" ) ).append( " (" ).append( System.getProperty( "java.vendor" ) ).append( ")\n" )
                .append( "JVM     = "         ).append( System.getProperty( "java.vm.name" ) ).append( " v." ).append( System.getProperty( "java.vm.version" ) ).append( '\n' )
                .append( "JRE     = "         ).append( System.getProperty( "java.runtime.name" ) ).append( ". Version: " ).append( System.getProperty( "java.runtime.version" ) ).append( '\n' )
                .append( "JVM RAM = "         ).append( nUsedRAM ).append( " Mb used of " ).append( nTotRAM ).append( " Mb (Max to alloc: " ).append( nMaxRAM ).append( " Mb)\n" )
                .append( "Locale  = "         ).append( Locale.getDefault() ).append( '\n' )
                .append( "OS      = "         ).append( System.getProperty( "os.name" ) ).append( ". Version: " ).append( System.getProperty( "os.version" ) ).append( ". Architecture: " ).append( System.getProperty( "os.arch" ) ).append( '\n' )
                .append( "IP(s)   = "         ).append( StdXprFns.invoke( "localIPs", (Object[]) null ).toString() ).append( '\n' )
                .append( "Docker  = "         ).append( bDocker ).append( " -> Apparently Stick is " ).append( bDocker ? "" : "not" ).append( " running inside a docker" ).append ( '\n' ).append( '\n' )
                .append( sGridMsg             ).append( '\n' )
                .append( '[' ).append( LocalDateTime.now().format( DateTimeFormatter.ofPattern( "yyyy-MM-dd HH:mm:ss" ) ) ).append( "] Stick started..." ).append('\n')
                .toString();

        say( sInfo );

        System.clearProperty( "_GridManager_toString_Message_" );   // Not needed any more

        //------------------------------------------------------------------------//
        // Prepare and start the Event Bus
        // When ExEn Grid, those ExEns connecting later will loose events launched by those ExEns that started earlier: this is the expected behaviour.

        eventBus.add( new BusListener() )
                .start();

        //------------------------------------------------------------------------//
        // Collect devices downtimed (those that apparently do not work any more)

        long   nDownTime   = config.get( "exen", "downtimed_interval"     , 0  ) * 1000;
        String sDownDevice = config.get( "exen", "downtimed_report_device", "" );

        if( (nDownTime > 0) && UtilStr.isNotEmpty( sDownDevice ) )
        {
            nDownTime = (nDownTime < 1000 ? 1000 : nDownTime);

            if( deviMgr.named( sDownDevice ) != null )
            {
                UtilSys.executor( false )
                       .delay( nDownTime )
                       .rate( nDownTime )
                       .execute( () -> checkDowntimedDevices( sDownDevice ) );
            }
            else
            {
                log( ILogger.Level.WARNING, '"'+ sDownDevice +"\" device does not exist; downtimed task not initiated" );
            }
        }

        return this;
    }

    @Override
    public String toString()
    {
        return "Stick version "+ UtilSys.getVersion( getClass() );
    }

    // equals and hascode are not needed: the default Java implementation for these methods is OK

    //------------------------------------------------------------------------//
    // BY IMPLEMENTING IRuntime

    @Override
    public ICommand[] all( String... asClass )
    {
        int mask;   // Bitmask: 1=device, 2=driver, 4=script, 8=rule, 16=library

        if( asClass == null || asClass.length == 0 )
        {
            mask = 1 | 2 | 4 | 8 | 16;   // all
        }
        else
        {
            int m = 0;

            for( String s : asClass )
            {
                m |= classMask( s );

                if( m == (1 | 2 | 4 | 8 | 16) )
                    break;                 // early exit if everything requested
            }

            mask = m;
        }

        // Fast-path when only one bit is set
        if( Integer.bitCount( mask ) == 1 )
        {
            if( (mask &  1) != 0 ) return deviMgr.getAll().toArray( ICommand[]::new );
            if( (mask &  2) != 0 ) return drvrMgr.getAll().toArray( ICommand[]::new );
            if( (mask &  4) != 0 ) return srptMgr.getAll().toArray( ICommand[]::new );
            if( (mask &  8) != 0 ) return ruleMgr.getAll().toArray( ICommand[]::new );
         /* else */                return librMgr.getAll().toArray( ICommand[]::new );
        }

        // Generic case
        List<ICommand> list = new ArrayList<>( 128 );

        if( (mask &  1) != 0 )  list.addAll( deviMgr.getAll() );
        if( (mask &  2) != 0 )  list.addAll( drvrMgr.getAll() );
        if( (mask &  4) != 0 )  list.addAll( srptMgr.getAll() );
        if( (mask &  8) != 0 )  list.addAll( ruleMgr.getAll() );
        if( (mask & 16) != 0 )  list.addAll( librMgr.getAll() );

        return list.toArray( ICommand[]::new );
    }

    @Override
    public ICommand get( String sName )
    {
        assert sName != null;

        ICommand cmd;

        // From most to least frequent -->

        cmd = deviMgr.named( sName );  if( cmd != null ) return cmd;
        cmd = ruleMgr.named( sName );  if( cmd != null ) return cmd;
        cmd = srptMgr.named( sName );  if( cmd != null ) return cmd;
        cmd = drvrMgr.named( sName );  if( cmd != null ) return cmd;
        cmd = librMgr.named( sName );

        return cmd;   // Either the command or null
    }

    @Override
    public void addModel( String sModelJSON )
    {
        if( UtilStr.isNotEmpty( sModelJSON ) )
        {
            try
            {
                List<ICommand> lstCmds = new ArrayList<>();
                ICmdEncDecLib  builder = this.config.newCILBuilder();
                JsonObject     joModel = Json.parse( sModelJSON ).asObject();
                String         version = joModel.getString( "code-version", "unknown" );

                if( ! version.equals( "1.0" ) )
                    failed( null, "Invalid transpiled code version: "+ version );

                joModel.get( "commands" )
                       .asArray()
                       .forEach( (JsonValue jv) -> lstCmds.add( builder.build( jv.toString() ) ) );

                if( lstCmds.isEmpty() )
                {
                    log( ILogger.Level.WARNING, "There are no commands in script: this is valid, but strange." );
                }
                else
                {
                    for( ICommand cmd : sortByType( lstCmds, false ) )
                        add( cmd );
                }
            }
            catch( ParseException exc )
            {
                failed( exc, null );
            }
        }
    }

    @Override
    public void add( ICommand... commands )
    {
        List<ICommand> list = new ArrayList<>( commands.length );

        for( ICommand command : commands )
        {
            if( command == null )  log( ILogger.Level.SEVERE, "Invalid command 'null'" );
            else                   list.add( command );
        }

        for( ICommand command : sortByType( list, false ) )
        {
            if( command instanceof ILibrary )  { librMgr.add( (ILibrary) command ); continue; }
            if( command instanceof IDriver  )  { drvrMgr.add( (IDriver)  command ); continue; }
            if( command instanceof IScript  )  { srptMgr.add( (IScript)  command ); continue; }
            if( command instanceof IRule    )  { ruleMgr.add( (IRule)    command ); continue; }

            eventBus.pause();

            IDevice device = (IDevice) command;

            if( drvrMgr.add( device ) )
                deviMgr.add( device );

            eventBus.resume();

            // When adding multiple commands, sortByType() ensures prerequisites come first
            // (Script before Driver, Driver before Device), so no orphan cleanup is needed.

            // drvrMgr.clean() / srptMgr.clean() are intentionally NOT called here:
            // a Driver just added may have no devices yet (they may arrive in a later add() call).
            // Calling clean() at this point would incorrectly remove a newly-added Driver.

            // Any orphan left by a partially-failed add() will be swept by the next remove() call.
        }
    }

    @Override
    public boolean remove( ICommand... commands )
    {
        boolean allOK = true;

        List<ICommand> list = new ArrayList<>( commands.length );

        for( ICommand command : commands )
        {
            if( command == null )  { log( ILogger.Level.SEVERE, "Removing 'null'" ); allOK = false; }
            else                   list.add( command );
        }

        for( ICommand command : sortByType( list, true ) )
        {
            eventBus.pause();

            boolean bOK;

                 if( command instanceof ILibrary )  bOK = librMgr.remove( (ILibrary) command );
            else if( command instanceof IDriver  )  bOK = drvrMgr.remove( (IDriver)  command );
            else if( command instanceof IScript  )  bOK = srptMgr.remove( (IScript)  command );
            else if( command instanceof IRule    )  bOK = ruleMgr.remove( (IRule)    command );
            else
            {
                IDevice device = (IDevice) command;

                bOK = deviMgr.remove( device ) &&
                      drvrMgr.remove( device );     // This method removes the driver if it is not needed anymore (has no more devices)
            }

            if( bOK )
            {
                drvrMgr.clean();
                srptMgr.clean();
            }

            eventBus.resume();

            allOK &= bOK;
        }

        return allOK;
    }

    @Override
    public boolean isNameOfGroup( String name )
    {
        return deviMgr.isGroup( name );
    }

    @Override
    public IDevice[] getMembersOf( String... group )
    {
        return deviMgr.getMembersOf( group ).toArray( IDevice[]::new );
    }

    @Override
    public IDevice[] getInAnyGroup( String... group )
    {
        return deviMgr.getInAnyGroup( group ).toArray( IDevice[]::new );
    }

    @Override
    public IDevice[] getInAllGroups( String... group )
    {
        return deviMgr.getInAllGroups( group ).toArray( IDevice[]::new );
    }

    @Override
    public String[] getGroupMemberNames( String group )
    {
        return deviMgr.getGroupMemberNames( group );
    }

    @Override
    public IXprEval newXprEval()
    {
        return config.newXprEval();
    }

    @Override
    public ICandi.IBuilder newLanguageBuilder()
    {
        return config.newLanguageBuilder();
    }

    @Override
    public IEventBus bus()
    {
        return eventBus;
    }

    @Override
    public <T> T getFromConfig( String module, String varName, T defValue )
    {
        return config.get( module, varName, defValue );
    }

    @Override
    public boolean isGridNode()
    {
        return gridMgr != null;
    }

    @Override
    public Stick log( ILogger.Level level, Object msg )
    {
        ILogger logger = UtilSys.getLogger();

        if( isLoggable( level ) )
        {
            String sMsg = ((msg == null) ? "Error has no description" : msg.toString());    // Will be null only by mistake, but has to be checked

            if( logger == null )
            {
                System.err.println( msg );
            }
            else
            {
                logger.log( level, sMsg );

                if( isGridNode() && level.weight >= ILogger.Level.WARNING.weight )    // Only WARNING and SEVERE are broadcasted (if WARNING is loggable, SEVERE will be too).
                {
                    Throwable exc = (msg instanceof Throwable) ? (Throwable) msg : new MingleException( sMsg );
                    gridMgr.broadcast( exc );
                }
            }
        }

        return this;
    }

    @Override
    public boolean isLoggable( ILogger.Level level )
    {
        return UtilSys.getLogger() != null &&
               UtilSys.getLogger().isLoggable( level );
    }

    @Override
    public IRuntime exit( int millis )
    {
        return exit( millis, 0, null );
    }

    @Override
    public IRuntime exit( int millis, int exitCode, Object reason )
    {
        synchronized( this )
        {
            if( bExited )       // To avoid more than one call to ::exit(...)
                return this;

            bExited = true;
        }

        if( reason != null )
            say( UtilStr.toString( reason ) );


        // Using this does not work (I do not know why) -->
        //      UtilSys.execute( getClass().getName(), millis, () -> System.exit( 0 ) );

        try
        {
            if( millis > 0 )
                Thread.sleep( millis );
        }
        catch( InterruptedException e )
        {
            // Nothing to do
        }
        finally
        {
            System.exit( exitCode );    // There is a JVM hook that will invoke ::stop()
        }

        return this;
    }

    //------------------------------------------------------------------------//
    // PRIVATE SCOPE

    private IRuntime say( String msg )
    {
        if( UtilSys.getLogger() != null )
            UtilSys.getLogger().say( msg );
        else
            System.out.println( msg );

        return this;
    }

    /**
     * Informs to a device about the down-timed devices.
     *
     * @param sReporterDevName The name of the device to be informed: the one that receives the list of down-timed devices.
     */
    private void checkDowntimedDevices( final String sReporterDevName )
    {
        IDevice dev2Report = deviMgr.named( sReporterDevName );    // The device used to store the list of downtimed devices

        if( dev2Report != null )    // Because devices can be deleted at runtime
        {
            list lst = new list();

            deviMgr.forEach( dev ->
                             {
                                if( dev.isDowntimed() )
                                    lst.add( dev.name() );
                             } );

            if( ! lst.isEmpty() )
                dev2Report.value( lst );
        }
    }

    private void failed( Exception exc, String msg )
    {
        if( msg == null )
            msg = "";

        msg += "\nCan not continue. Check logs.\n\n"+ UtilStr.toString( exc );

        exit( 0, 1, msg );    // ::stop() is always invoked by a System hook
    }

    // There is a hook that invokes this method on JMV exiting
    private Stick stop()
    {
        if( bExited )
            return this;

        // In case the runVoidThread() method was invoked -------------
        if( ! keepRun )
            return this;   // Already stopped

        say( "Shutting down Stick ..." );

        keepRun = false;   // Signal thread to stop

        synchronized( this.config )
        {
            this.config.notifyAll();   // Wake up the void thread so it can exit the loop
        }
        //-------------------------------------------------------------

        // Execute PRE ONSTOP scripts BEFORE stopping EventBus
        // (scripts can still communicate with devices via the bus)
        srptMgr.runPreStopScripts();

        eventBus.flush();  // Wait for PRE ONSTOP messages to be delivered
        eventBus.stop();
        ruleMgr.stop();
        drvrMgr.stop();
        deviMgr.stop();

        if( isGridNode() )
            gridMgr.stop();

        srptMgr.stop();    // Last one to trigger SCRIPTs ONSTOP after all is stopped (entities are gone)

        UtilSys.stop();

        try
        {
            Thread.sleep( 2500 );   // A long delay time (there is no rush, guys) to allow any pending tasks (if any) to finish
        }
        catch( InterruptedException e )
        {
            // Nothing to do
        }

        say( "<<<<<<< Stick finished >>>>>>>" );

        return this;
    }

    /**
     * Sorts passed list in the needed order to be added (or removed): Scripts, Drivers, Devices and Rules.
     *
     * @param commands List to be sorted.
     * @param bReverse true when the resulting list is needed to remove commands instead of adding them.
     * @return Passed list after being sorted
     */
    private List<ICommand> sortByType( List<ICommand> list, boolean bReverse )
    {
        if( list.size() > 1 )
        {
            list.sort( (cmd1, cmd2) -> getPrecedence( cmd1 ).compareTo( getPrecedence( cmd2 ) ) );

            if( bReverse )
                Collections.reverse( list );
        }

        return list;
    }

    private Integer getPrecedence( ICommand cmd )
    {
             if( cmd instanceof ILibrary )  return 0;    // Highest precedence: functions must be available before scripts
        else if( cmd instanceof IScript  )  return 1;
        else if( cmd instanceof IDriver  )  return 2;
        else if( cmd instanceof IDevice  )  return 3;
                                            return 4;    // Lowest precedence (IRule)
    }

    /**
     * JVM needed at least one daemon thread to not exit: this approach (to create a void
     * thread) is as good as any other approach.
     * <p>
     * The thread lives in the JVM and there is no need to have a reference to this thread:
     * the only case this reference would be needed is to stop this thread, but this is done
     * only when Stick is going to be stopped, and it is simpler to invoke System.exit(0):
     * this stops all threads, invokes the shutdown-hooks and exists.
     */
    private void runVoidThread()
    {
        Thread voidTh = new Thread( () ->
            {
                while( keepRun )
                {
                    synchronized( Stick.this.config )     // Config -> just a final var
                    {
                        try
                        {
                            Stick.this.config.wait();
                        }
                        catch( InterruptedException e )   // Handle interruption to exit loop
                        {
                            break;
                        }
                    }
                }
            } );

        voidTh.setName( "Stick-KeepAlive" );
        voidTh.start();
    }

    private static int classMask( String s )    // s --> Class Name (Device, Script, Rule, Library)
    {
        if( s == null )
            return 0;

        // 1. Manual Trim (Zero Allocation)
        int start = 0, end = s.length();

        while( start < end && Character.isWhitespace( s.charAt( start ) ) )
            start++;

        while( end > start && Character.isWhitespace( s.charAt( end - 1 ) ) )
            end--;

        // 2. Manual Plural Check
        if( end > start )
        {
            char last = s.charAt( end - 1 );

            if( last == 's' || last == 'S' )
                end--;
        }

        int len = end - start;

        if( len == 0 )
            return 0;

        // 3. Switch on first char to reduce comparison cost
        //    We bitwise-OR with 32 to force lowercase (ASCII trick) for the char check
        char first = s.charAt( start );

        switch( first | 32 )    // 'D' | 32 = 'd', 'R' | 32 = 'r'
        {
            case 'd':
                if( len == 6 )
                {
                    // Only check "device" or "driver" if length matches 6
                    // Differentiating by the second char 'e' vs 'r' is even faster
                    char second = s.charAt( start + 1 );

                    if( (second | 32) == 'e' && s.regionMatches( true, start, "device", 0, 6 ) )
                        return 1;

                    if( (second | 32) == 'r' && s.regionMatches( true, start, "driver", 0, 6 ) )
                        return 2;
                }
                break;

            case 's':
                if( len == 6 && s.regionMatches( true, start, "script", 0, 6 ) )
                    return 4;

                break;

            case 'r':
                if( len == 4 && s.regionMatches( true, start, "rule", 0, 4 ) )
                    return 8;

                break;

            case 'l':
                if( len == 7 && s.regionMatches( true, start, "library", 0, 7 ) )
                    return 16;

                break;
        }

        return 0;
    }

    //----------------------------------------------------------------------------//
    // INNER CLASS
    // A Bus Listener to read message (mainly form Controllers).
    //---------------------------------------------------------------------------//

    /**
     * This is just an interface needed by the BusListener class.
     */
    @FunctionalInterface
    private interface MessageHandler
    {
        void handle( Message message );
    }

    /**
     * BusListener: this class is the messages orchestrator for the bus.
     *
     * When arrived to destinations, messages are processed by the inner class
     * ::ClientListener. In other words, from the point of the view of clients
     * connected to an ExEn, ::BusListener is the one that sends messages to
     * the clients and ::ClientListener the one that receives messages from them.
     *
     * An ExEn sends only messages produced by itself (using a NetServer),
     * therefore an ExEn can not resend messages received from another ExEn or
     * tool (like Glue or Gum), but messages to be sent are sent to every
     * connected entity (using INetClient).
     */
    private final class BusListener implements IEventBus.Listener<com.peyrona.mingle.lang.messages.Message>
    {
        private final Map<Class<?>, MessageHandler> msgHandler;       // Pre-computed dispatch map for O(1) message routing
        private final Map<String  , IDriver>        driver4device;    // Driver associated with a device (by its name)

        @Override
        public void onMessage( Message message )
        {
            msgHandler.get( message.getClass() )
                      .handle( message );    // If there is no handler for the messsage, a null point exc is triggered: this is intended
        }

        //------------------------------------------------------------------------//
        // PRIVATE INTERFACE

        private BusListener()
        {
            driver4device = new HashMap<>( 5 );

            msgHandler = Map.of( MsgDeviceReaded.class  , this::handleDeviceReaded,
                                 MsgDeviceChanged.class , this::handleDeviceChanged,
                                 MsgChangeActuator.class, this::handleChangeActuator,
                                 MsgExecute.class       , this::handleExecute,
                                 MsgReadDevice.class    , this::handleReadDevice );
        }

        private void handleDeviceReaded( Message message )
        {
            final MsgDeviceReaded msg = (MsgDeviceReaded) message;

            // If message::isOwn is true  the device exists because the msg was generated in this ExEn.
            // If message::isOwn is false the device exists because it was checked by ::ServerListener.

            if( msg.isOwn )
            {
                if( deviMgr.named( msg.name ).value( msg.value ) )    // If device effectively changed its value
                {
                    ruleMgr.forEach( rule -> rule.eval( msg.name, msg.value ) );
                    broadcast( message );
                }
            }
            else
            {
                ruleMgr.forEach( rule -> rule.eval( msg.name, msg.value ) );
            }
        }

        private void handleDeviceChanged( Message message )
        {
            final MsgDeviceChanged msg = (MsgDeviceChanged) message;

            // If message::isOwn is true  the device exists because the msg was generated in this ExEn.
            // If message::isOwn is false the device exists because it was checked by ::ServerListener.

            if( msg.isOwn )
            {
                if( deviMgr.named( msg.name ).value( msg.value ) )    // If device effectively changed its value
                {
                    ruleMgr.forEach( rule -> rule.eval( msg.name, msg.value ) );
                    broadcast( message );
                }
            }
            else
            {
                ruleMgr.forEach( rule -> rule.eval( msg.name, msg.value ) );
            }
        }

        private void handleChangeActuator( Message message )
        {
            final MsgChangeActuator msg    = (MsgChangeActuator) message;
            final IDriver           driver = getDriver4Device( msg.name );

            // If message::isOwn is true  the device exists because the msg was generated in this ExEn.
            // If message::isOwn is false the device exists because it was checked by ::ServerListener.

            if( driver != null )     // There could be a problem loading the driver
                driver.write( msg.name, msg.value );
            else
                log( ILogger.Level.SEVERE, "Driver for device '"+ msg.name +"' was not found" );

            broadcast( message );    // Perhaps an actuator with same name is in another grid node
        }

        private void handleExecute( Message message )
        {
            final MsgExecute msg  = (MsgExecute) message;
            final IRule      rule = ruleMgr.named( msg.name );

            // If message::isOwn is true  the rule/script exists because the msg was generated in this ExEn.
            // If message::isOwn is false the rule/script exists because it was checked by ::ServerListener.

            if( rule != null )
                rule.trigger( (boolean) msg.value );
            else    // Must be an script
                srptMgr.named( msg.name ).execute();

            broadcast( message );    // Perhaps a rule or script with same name is in another grid node
        }

        private void handleReadDevice( Message message )
        {
            final MsgReadDevice msg    = (MsgReadDevice) message;
            final IDriver       driver = getDriver4Device( msg.name );

            // If message::isOwn is true  the device exists because the msg was generated in this ExEn.
            // If message::isOwn is false the device exists because it was checked by ::ServerListener.

            if( driver != null )     // There could be a problem loading the driver
                driver.read( msg.name );
            else
                log( ILogger.Level.SEVERE, "Driver for device '"+ msg.name +"' was not found" );

            broadcast( message );    // Perhaps a rule or script with same name is in another grid node
        }

        private void broadcast( Message message )
        {
            if( message.isOwn && isGridNode() )
                gridMgr.broadcast( message );   // Internally uses a thread
        }

        private IDriver getDriver4Device( String name )
        {
            IDriver driver = driver4device.get( name );

            if( driver == null )
            {
                driver = drvrMgr.first( drv -> drv.has( name ) );

                if( driver != null )
                {
                    driver4device.put( name, driver );
                }
                else if( deviMgr.named( name ) != null )    // Only an error if the device still exists (1)
                {
                    log( ILogger.Level.SEVERE, "No driver for device '"+ name +"'\nCheck Stick log file." );
                }
            }

            return driver;

            // (1) When eventBus.resume() is called after each removal step, in-flight MsgReadDevice
            //     messages for already-removed devices are flushed. The handler logs SEVERE because
            //     the driver is gone — but the device is simply gone too.
        }
    }
}