
package com.peyrona.mingle.glue.exen.tables;

import com.peyrona.mingle.glue.gswing.GDialog;
import com.peyrona.mingle.glue.gswing.GTable;
import java.awt.BorderLayout;
import java.awt.Dialog;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author Francisco José Morero Peyrona
 *
 * Official web site at: <a href="https://github.com/peyrona/mingle">https://github.com/peyrona/mingle</a>
 */
final class DlgTableConfig extends javax.swing.JPanel
{
    private final GTable table;

    //------------------------------------------------------------------------//

    static void show( GTable table, String sFilterLabel )
    {
        DlgTableConfig panel = new DlgTableConfig( table, sFilterLabel );

        GDialog dlg = new GDialog( "Table config", Dialog.ModalityType.DOCUMENT_MODAL );
                dlg.add( panel, BorderLayout.CENTER );
                dlg.addWindowListener( new WindowAdapter()
                                        {   @Override
                                            public void windowClosing( WindowEvent we )
                                            {
                                                int     nMaxRows = (Integer) panel.spnMaxRows.getValue();
                                                String  sFilter  = panel.txtFilter.getText();             // Never null
                                                boolean isRegExp = panel.chkRegExp.isSelected();

                                                if( table.getMaxRows() != nMaxRows )
                                                    panel.table.setMaxRows( nMaxRows );

                                                if( (isRegExp != table.isFilterRegExp()) || (! sFilter.equals( table.getFilter() )) )
                                                    panel.table.setFilter( sFilter, isRegExp );
                                            }
                                        } );
                dlg.setVisible();
    }

    //------------------------------------------------------------------------//

    /**
     * Creates new form DlgTableConfig
     */
    private DlgTableConfig( GTable table, String sFilterLabel )
    {
        this.table = table;

        initComponents();

        spnMaxRows.setValue( table.getMaxRows() );
        chkRegExp.setSelected( table.isFilterRegExp() );
        txtFilter.setText( table.getFilter() );
        lblFilter.setText( sFilterLabel );
        btnClearTable.addActionListener( (ae) -> table.empty() );
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        spnMaxRows = new javax.swing.JSpinner();
        btnClearTable = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblFilter = new javax.swing.JLabel();
        txtFilter = new javax.swing.JTextField();
        chkRegExp = new javax.swing.JCheckBox();

        jLabel1.setText("Maximum rows to show");

        spnMaxRows.setModel(new javax.swing.SpinnerNumberModel(200, 0, null, 5));

        btnClearTable.setText("Clear table");
        btnClearTable.setDefaultCapable(false);

        jLabel2.setFont(jLabel2.getFont().deriveFont(jLabel2.getFont().getSize()-2f));
        jLabel2.setText("(0 for unlimited)");

        lblFilter.setText("Filter");

        chkRegExp.setText("Is RegExpr");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnMaxRows, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addComponent(txtFilter)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFilter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkRegExp))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnClearTable)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spnMaxRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFilter)
                    .addComponent(chkRegExp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnClearTable)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearTable;
    private javax.swing.JCheckBox chkRegExp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFilter;
    private javax.swing.JSpinner spnMaxRows;
    private javax.swing.JTextField txtFilter;
    // End of variables declaration//GEN-END:variables
}
